parameters:
    assetic.twig_extension.class: "Troopers\\AsseticInjectorBundle\\Twig\\AsseticExtension"
    troopers_assetic_injector.collector.class: "Troopers\\AsseticInjectorBundle\\AssetsCollector\\Collector"

services:

    troopers_assetic_injector.collector:
        class: '%troopers_assetic_injector.collector.class%'
        arguments: ["@service_container"]

    troopers_assetic_injector.collector_engine.require_all:
        class: "Troopers\\AsseticInjectorBundle\\AssetsCollector\\RequireAll"

    assetic_injector.require_all:
        alias: troopers_assetic_injector.collector_engine.require_all

    assetic.twig_extension:
        class: '%assetic.twig_extension.class%'
        public: false
        tags:
            - {name: twig.extension}
            - {name: assetic.templating.twig}
        arguments: ["@assetic.asset_factory", "@templating.name_parser", '%assetic.use_controller%', '%assetic.twig_extension.functions%', '%assetic.bundles%', "@assetic.value_supplier" ]
        calls:
            - [ setCollector, [ "@troopers_assetic_injector.collector" ] ]
